version: '3.8'
services:
  wordpress:
    build:
      context: ./plugins/wpe-headless
      dockerfile: ../../.docker/dockerfile.wordpress
    restart: always
    links:
      - frontend
    ports:
      - 8096:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - wordpress:/var/www/html
      - ./plugins/wpe-headless:/var/www/html/wp-content/plugins/wpe-headless
    command: /bin/sh -c "wp plugin install wp-graphql --activate --allow-root && wp db export /var/www/html/wp-content/plugins/wpe-headless/tests/_data/dump.sql --allow-root && apache2-foreground"
  
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 33066:3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
    volumes:
      - ./plugins/wpe-headless/.docker/mysql:/docker-entrypoint-initdb.d
  
  frontend:
    build:
      context: ./examples/next/getting-started
      dockerfile: ../../../.docker/dockerfile.frontend
    restart: always
    ports:
      - 8097:3000
    environment:
      NEXT_PUBLIC_WORDPRESS_URL: http://wordpress
      WP_HEADLESS_SECRET: 00000000-0000-0000-0000-000000000001
    command: /bin/sh -c "./wait-for-it.sh wordpress:80 -- npm run build && npm run start"
  
  webdriver:
    image: selenium/standalone-chrome:latest
    restart: always
    ports:
      - 9515:4444

volumes:
  wordpress:
  db:
  frontend:
