name: E2E Codecept Tests
on: pull_request
jobs:
  e2e-codecept:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build containers
        run: docker-compose up -d
      - name: Check containers
        run: sleep 10 && docker ps -a
      - name: Test
        run: |
          docker \
            exec \
            --workdir=/var/www/html/wp-content/plugins/wpe-headless \
            $(docker-compose ps -q wordpress) \
            wait-for-it --timeout=30 --strict frontend:3000 -- vendor/bin/codecept run acceptance
